# ===============================
# CONFIGURACIÓN DEL SERVIDOR
# ===============================
# Puerto donde correrá este microservicio 
server.port=8082
spring.application.name=microservicio-cuenta

# ===============================
# CONFIGURACIÓN DE BASE DE DATOS (H2)
# ===============================
# URL de conexión: 'mem:cuentadb' 
spring.datasource.url=jdbc:h2:mem:cuentadb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# ===============================
# JPA / HIBERNATE
# ===============================
# 'update' crea las tablas automáticamente basadas en los @Entity
spring.jpa.hibernate.ddl-auto=update
# Muestra las consultas SQL que Spring hace en la consola 
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# ===============================
# CONSOLA H2 (Interfaz Gráfica)
# ===============================
# Permite entrar a http://localhost:8080/h2-console para ver las tablas
spring.h2.console.enabled=true
# Esto es importante para que el navegador no bloquee la consola de H2
spring.h2.console.settings.web-allow-others=true
spring.h2.console.path=/h2-console

# ===============================
# LOGGING
# ===============================
logging.level.org.springframework.web=INFO