spring.application.name=usuarios
server.port=8082

spring.datasource.url=jdbc:h2:mem:usuariosDB
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.h2.console.settings.web-allow-others=true
spring.security.user.name=admin
spring.security.user.password=admin

# Configuraci\u00f3n de Gmail para la Defensor\u00eda
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=jair100flo@gmail.com
spring.mail.password=rozzvatswkacxvqf
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true