# Configuración de H2 en memoria
spring.datasource.url=jdbc:h2:mem:defensoriadb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Consola de H2 para que puedas ver las tablas en el navegador
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Crear tablas automáticamente basado en tus Entities
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

server.port=8082