spring.application.name=quejoso
server.port=8080

# Base de datos
spring.datasource.url=jdbc:h2:mem:defensoria_db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Consola H2 - Forzado
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
# Esta l\u00ednea es clave para evitar el error 999/404 en versiones 3.x
spring.h2.console.settings.web-allow-others=true

# Seguridad de Frames
spring.headers.frame-options.policy=sameorigin

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true