spring.application.name=quejoso
server.port=8080

# Base de datos
spring.datasource.url=jdbc:h2:mem:defensoria_db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# CONSOLA H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# IMPORTANTE: Para que no se vea blanco al entrar
spring.headers.frame-options.policy=SAMEORIGIN

# JPA / Hibernate ? lee las entidades y crea/actualiza las tablas automáticamente
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#importante para el envío de correos
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=jair100flo@gmail.com
spring.mail.password=rozzvatswkacxvqf
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# Ejecuta el data.sql siempre al iniciar
spring.sql.init.mode=always

# Espera a que Hibernate cree las tablas antes de insertar los datos
spring.jpa.defer-datasource-initialization=true