spring.application.name=quejoso
server.port=8080

# Base de datos
spring.datasource.url=jdbc:h2:mem:defensoria_db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# CONSOLA H2 (Asegúrate de que estas dos líneas estén así)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# IMPORTANTE: Para que no se vea blanco al entrar
spring.headers.frame-options.policy=SAMEORIGIN

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true