--
-- PostgreSQL database dump
--

\restrict 2IdUd2qjYWmW63fM2Jti6NTZ3tgLIlgfXRyZ8iTBY0ocf8Hl1Eb1ByT0cHXcT3R

-- Dumped from database version 16.14 (Debian 16.14-1.pgdg13+1)
-- Dumped by pg_dump version 16.14 (Debian 16.14-1.pgdg13+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: acuerdos_conciliacion; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.acuerdos_conciliacion (
    id bigint NOT NULL,
    asunto character varying(255) NOT NULL,
    comentario_quejoso text,
    correo_institucional character varying(255) NOT NULL,
    creado_por character varying(255),
    estado character varying(255) NOT NULL,
    fecha_emision timestamp(6) without time zone,
    fecha_respuesta timestamp(6) without time zone,
    numero_folio character varying(255) NOT NULL,
    terminos text NOT NULL
);


ALTER TABLE public.acuerdos_conciliacion OWNER TO postgres;

--
-- Name: acuerdos_conciliacion_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.acuerdos_conciliacion ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.acuerdos_conciliacion_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: acuerdos_conclusion; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.acuerdos_conclusion (
    id bigint NOT NULL,
    concluido boolean NOT NULL,
    expediente_id bigint NOT NULL,
    fecha_creacion timestamp(6) without time zone NOT NULL,
    fecha_envio_secretarial timestamp(6) without time zone,
    folio character varying(50) NOT NULL,
    ruta_pdf_generado character varying(300),
    texto_acuerdo text NOT NULL
);


ALTER TABLE public.acuerdos_conclusion OWNER TO postgres;

--
-- Name: acuerdos_conclusion_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.acuerdos_conclusion ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.acuerdos_conclusion_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: bitacora_acciones; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.bitacora_acciones (
    id bigint NOT NULL,
    accion_realizada character varying(255) NOT NULL,
    fecha timestamp(6) without time zone NOT NULL,
    ip character varying(255) NOT NULL,
    usuario character varying(255) NOT NULL
);


ALTER TABLE public.bitacora_acciones OWNER TO postgres;

--
-- Name: bitacora_acciones_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.bitacora_acciones ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.bitacora_acciones_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: citas_primer_contacto; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.citas_primer_contacto (
    id bigint NOT NULL,
    analista_id bigint NOT NULL,
    analista_nombre character varying(150),
    estatus character varying(50) NOT NULL,
    expediente_id bigint NOT NULL,
    fecha_cita date NOT NULL,
    fecha_creacion timestamp(6) without time zone NOT NULL,
    folio character varying(50) NOT NULL,
    hora_cita time(6) without time zone NOT NULL,
    motivo text NOT NULL,
    quejoso_id bigint,
    quejoso_nombre character varying(150),
    tipo_cita character varying(50) NOT NULL
);


ALTER TABLE public.citas_primer_contacto OWNER TO postgres;

--
-- Name: citas_primer_contacto_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.citas_primer_contacto ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.citas_primer_contacto_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: dependencias; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.dependencias (
    id bigint NOT NULL,
    abreviatura character varying(30),
    activo boolean NOT NULL,
    categoria character varying(150),
    clave character varying(20) NOT NULL,
    clave_padre character varying(20),
    creado_en timestamp(6) without time zone,
    nivel integer NOT NULL,
    nombre character varying(255) NOT NULL,
    notas text,
    pagina_manual integer,
    tipo character varying(60) NOT NULL,
    correo_contacto character varying(150),
    nombre_titular character varying(150)
);


ALTER TABLE public.dependencias OWNER TO postgres;

--
-- Name: dependencias_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.dependencias ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.dependencias_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: dictamenes_primer_contacto; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.dictamenes_primer_contacto (
    id bigint NOT NULL,
    analista_id bigint NOT NULL,
    analista_nombre character varying(150),
    area_turno character varying(150),
    expediente_id bigint NOT NULL,
    fecha_dictamen timestamp(6) without time zone NOT NULL,
    folio character varying(50) NOT NULL,
    justificacion text NOT NULL,
    observaciones text,
    responsable_turno character varying(150),
    resultado character varying(50) NOT NULL
);


ALTER TABLE public.dictamenes_primer_contacto OWNER TO postgres;

--
-- Name: dictamenes_primer_contacto_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.dictamenes_primer_contacto ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.dictamenes_primer_contacto_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: evidencias_primer_contacto; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.evidencias_primer_contacto (
    id bigint NOT NULL,
    evidencia_origen_id bigint,
    expediente_id bigint NOT NULL,
    fecha_carga character varying(50),
    nombre_archivo character varying(255),
    tipo_archivo character varying(100),
    url_archivo character varying(1000)
);


ALTER TABLE public.evidencias_primer_contacto OWNER TO postgres;

--
-- Name: evidencias_primer_contacto_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.evidencias_primer_contacto ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.evidencias_primer_contacto_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: expedientes_investigacion; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.expedientes_investigacion (
    id bigint NOT NULL,
    abogado_asesor_id bigint,
    abogado_asesor_nombre character varying(150),
    asunto character varying(200),
    descripcion_hechos text,
    estatus character varying(30) NOT NULL,
    fecha_actualizacion timestamp(6) without time zone,
    fecha_admision date NOT NULL,
    fecha_creacion timestamp(6) without time zone NOT NULL,
    folio character varying(50) NOT NULL,
    folio_origen character varying(50) NOT NULL,
    observaciones_analista text,
    quejoso_nombre character varying(150),
    unidad_academica character varying(100)
);


ALTER TABLE public.expedientes_investigacion OWNER TO postgres;

--
-- Name: expedientes_investigacion_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.expedientes_investigacion ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.expedientes_investigacion_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: expedientes_primer_contacto; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.expedientes_primer_contacto (
    id bigint NOT NULL,
    descripcion_hechos text,
    estatus character varying(40) NOT NULL,
    fecha_actualizacion timestamp(6) without time zone,
    fecha_creacion timestamp(6) without time zone NOT NULL,
    fecha_recepcion_origen character varying(50),
    folio character varying(50) NOT NULL,
    folio_origen character varying(50) NOT NULL,
    folio_subdefensoria character varying(50),
    prioridad character varying(30),
    quejoso_correo character varying(150),
    quejoso_id bigint,
    quejoso_nombre character varying(200),
    quejoso_telefono character varying(30),
    quejoso_tipo_usuario character varying(50),
    tema character varying(200),
    unidad_academica character varying(200)
);


ALTER TABLE public.expedientes_primer_contacto OWNER TO postgres;

--
-- Name: expedientes_primer_contacto_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.expedientes_primer_contacto ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.expedientes_primer_contacto_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: notas_analisis; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.notas_analisis (
    id bigint NOT NULL,
    analista_id bigint NOT NULL,
    analista_nombre character varying(150),
    contenido text NOT NULL,
    expediente_id bigint NOT NULL,
    fecha_actualizacion timestamp(6) without time zone,
    fecha_creacion timestamp(6) without time zone NOT NULL,
    folio character varying(50) NOT NULL
);


ALTER TABLE public.notas_analisis OWNER TO postgres;

--
-- Name: notas_analisis_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.notas_analisis ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.notas_analisis_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: notificaciones; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.notificaciones (
    id bigint NOT NULL,
    correo_destino character varying(255) NOT NULL,
    enlace character varying(255),
    fecha_creacion timestamp(6) without time zone,
    leida boolean NOT NULL,
    mensaje text,
    tipo character varying(255) NOT NULL,
    titulo character varying(255) NOT NULL
);


ALTER TABLE public.notificaciones OWNER TO postgres;

--
-- Name: notificaciones_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.notificaciones ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.notificaciones_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: oficios_informacion; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.oficios_informacion (
    id bigint NOT NULL,
    contenido_redactado text NOT NULL,
    correo_enviado boolean NOT NULL,
    destinatario_correo character varying(150) NOT NULL,
    destinatario_nombre character varying(200) NOT NULL,
    estatus character varying(20) NOT NULL,
    expediente_id bigint NOT NULL,
    fase character varying(30) NOT NULL,
    fecha_creacion timestamp(6) without time zone NOT NULL,
    fecha_envio date NOT NULL,
    fecha_limite date NOT NULL,
    folio character varying(50) NOT NULL,
    numero_oficio character varying(50) NOT NULL,
    ruta_pdf_generado character varying(300),
    tipo_plazo character varying(20) NOT NULL,
    unidad_academica character varying(100)
);


ALTER TABLE public.oficios_informacion OWNER TO postgres;

--
-- Name: oficios_informacion_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.oficios_informacion ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.oficios_informacion_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: personal_administrativo; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.personal_administrativo (
    id bigint NOT NULL,
    activo boolean NOT NULL,
    correo_institucional character varying(255) NOT NULL,
    cuenta_temporal boolean NOT NULL,
    fecha_creacion timestamp(6) without time zone NOT NULL,
    forzar_cambio_password boolean NOT NULL,
    nombre_completo character varying(255) NOT NULL,
    numero_empleado character varying(255) NOT NULL,
    password character varying(255) NOT NULL,
    rol character varying(255) NOT NULL,
    ultimo_login timestamp(6) without time zone,
    CONSTRAINT personal_administrativo_rol_check CHECK (((rol)::text = ANY (ARRAY[('ADMIN_SISTEMAS'::character varying)::text, ('RECEPCIONISTA'::character varying)::text, ('ANALISTA_PRIMER_CONTACTO'::character varying)::text, ('SUBDEFENSOR'::character varying)::text, ('DEFENSOR'::character varying)::text])))
);


ALTER TABLE public.personal_administrativo OWNER TO postgres;

--
-- Name: personal_administrativo_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.personal_administrativo ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.personal_administrativo_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: plantillas_documentos; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.plantillas_documentos (
    id bigint NOT NULL,
    activa boolean NOT NULL,
    actualizado_en timestamp(6) without time zone,
    actualizado_por character varying(255),
    contenido text NOT NULL,
    nombre character varying(255) NOT NULL,
    tipo character varying(80) NOT NULL
);


ALTER TABLE public.plantillas_documentos OWNER TO postgres;

--
-- Name: plantillas_documentos_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.plantillas_documentos ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.plantillas_documentos_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: preguntas_chatbot; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.preguntas_chatbot (
    id bigint NOT NULL,
    activo boolean NOT NULL,
    actualizado_en timestamp(6) without time zone,
    categoria character varying(80) NOT NULL,
    creado_en timestamp(6) without time zone,
    orden integer NOT NULL,
    pregunta character varying(300) NOT NULL,
    respuesta text NOT NULL
);


ALTER TABLE public.preguntas_chatbot OWNER TO postgres;

--
-- Name: preguntas_chatbot_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.preguntas_chatbot ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.preguntas_chatbot_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: queja_evidencias; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.queja_evidencias (
    id bigint NOT NULL,
    contenido bytea NOT NULL,
    fecha_subida timestamp(6) without time zone,
    nombre_archivo character varying(255) NOT NULL,
    tamanio_bytes bigint,
    tipo_mime character varying(255),
    queja_id bigint NOT NULL
);


ALTER TABLE public.queja_evidencias OWNER TO postgres;

--
-- Name: queja_evidencias_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.queja_evidencias ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.queja_evidencias_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: queja_tutores; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.queja_tutores (
    id bigint NOT NULL,
    apellido_materno character varying(255),
    apellido_paterno character varying(255),
    correo character varying(255),
    nombre character varying(255),
    parentesco character varying(255),
    telefono character varying(255),
    queja_id bigint NOT NULL
);


ALTER TABLE public.queja_tutores OWNER TO postgres;

--
-- Name: queja_tutores_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.queja_tutores ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.queja_tutores_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: quejas; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.quejas (
    id bigint NOT NULL,
    correo_institucional character varying(255) NOT NULL,
    descripcion text,
    fecha_creacion timestamp(6) without time zone,
    motivo character varying(255) NOT NULL,
    numero_folio character varying(255) NOT NULL,
    ruta_evidencia character varying(255),
    apellido_denunciado character varying(255),
    apellido_materno_quejoso character varying(255),
    apellido_paterno_quejoso character varying(255),
    fecha_hechos date,
    fecha_nacimiento_quejoso date,
    nombre_denunciado character varying(255),
    nombre_quejoso character varying(255),
    numero_identificacion_quejoso character varying(255),
    origen_registro character varying(255),
    tipo_identificacion_quejoso character varying(255),
    unidad_academica_clave character varying(255),
    estatus character varying(255),
    area_turnada character varying(255),
    comentarios_recepcion text,
    defensor_asignado character varying(255),
    fecha_recepcion_fisica date,
    fecha_turnado timestamp(6) without time zone,
    fecha_validacion timestamp(6) without time zone,
    motivo_rechazo text,
    numero_oficio character varying(255),
    tipo_documento_fisico character varying(255),
    tipo_usuario_manual character varying(255),
    ubicacion_fisica_expediente character varying(255),
    validado_por character varying(255),
    folio_primer_contacto character varying(255)
);


ALTER TABLE public.quejas OWNER TO postgres;

--
-- Name: quejas_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.quejas ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.quejas_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: recordatorios_urgencia; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.recordatorios_urgencia (
    id bigint NOT NULL,
    dias_retraso integer NOT NULL,
    fecha_envio timestamp(6) without time zone NOT NULL,
    medidas_ofrecidas text,
    mensaje text NOT NULL,
    oficio_id bigint NOT NULL
);


ALTER TABLE public.recordatorios_urgencia OWNER TO postgres;

--
-- Name: recordatorios_urgencia_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.recordatorios_urgencia ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.recordatorios_urgencia_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: remisiones_externas; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.remisiones_externas (
    id bigint NOT NULL,
    adjuntar_expediente boolean NOT NULL,
    analista_id bigint NOT NULL,
    analista_nombre character varying(150),
    autoridad_remision character varying(200) NOT NULL,
    expediente_id bigint NOT NULL,
    fecha_remision timestamp(6) without time zone NOT NULL,
    folio character varying(50) NOT NULL,
    justificacion_legal text NOT NULL,
    sugerencia_quejoso text
);


ALTER TABLE public.remisiones_externas OWNER TO postgres;

--
-- Name: remisiones_externas_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.remisiones_externas ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.remisiones_externas_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: respuestas_externas; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.respuestas_externas (
    id bigint NOT NULL,
    archivo_pdf_path character varying(300),
    canal_recepcion character varying(100) NOT NULL,
    expediente_id bigint NOT NULL,
    fecha_recepcion timestamp(6) without time zone NOT NULL,
    numero_oficio_respuesta_ua character varying(100),
    oficio_id bigint NOT NULL,
    resumen text NOT NULL
);


ALTER TABLE public.respuestas_externas OWNER TO postgres;

--
-- Name: respuestas_externas_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.respuestas_externas ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.respuestas_externas_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: usuarios; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.usuarios (
    id bigint NOT NULL,
    activo boolean NOT NULL,
    boleta character varying(255) NOT NULL,
    codigo_recuperacion character varying(255),
    correo_institucional character varying(255) NOT NULL,
    correo_personal character varying(255),
    fecha_expiracion_codigo timestamp(6) without time zone,
    nombre character varying(255) NOT NULL,
    nombre_tutor character varying(255),
    parentesco_tutor character varying(255),
    password character varying(255),
    telefono_celular character varying(255),
    telefono_tutor character varying(255),
    unidad_academica character varying(255),
    domicilio text
);


ALTER TABLE public.usuarios OWNER TO postgres;

--
-- Name: usuarios_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.usuarios ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.usuarios_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: acuerdos_conciliacion acuerdos_conciliacion_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.acuerdos_conciliacion
    ADD CONSTRAINT acuerdos_conciliacion_pkey PRIMARY KEY (id);


--
-- Name: acuerdos_conclusion acuerdos_conclusion_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.acuerdos_conclusion
    ADD CONSTRAINT acuerdos_conclusion_pkey PRIMARY KEY (id);


--
-- Name: bitacora_acciones bitacora_acciones_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.bitacora_acciones
    ADD CONSTRAINT bitacora_acciones_pkey PRIMARY KEY (id);


--
-- Name: citas_primer_contacto citas_primer_contacto_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.citas_primer_contacto
    ADD CONSTRAINT citas_primer_contacto_pkey PRIMARY KEY (id);


--
-- Name: dependencias dependencias_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.dependencias
    ADD CONSTRAINT dependencias_pkey PRIMARY KEY (id);


--
-- Name: dictamenes_primer_contacto dictamenes_primer_contacto_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.dictamenes_primer_contacto
    ADD CONSTRAINT dictamenes_primer_contacto_pkey PRIMARY KEY (id);


--
-- Name: evidencias_primer_contacto evidencias_primer_contacto_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.evidencias_primer_contacto
    ADD CONSTRAINT evidencias_primer_contacto_pkey PRIMARY KEY (id);


--
-- Name: expedientes_investigacion expedientes_investigacion_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.expedientes_investigacion
    ADD CONSTRAINT expedientes_investigacion_pkey PRIMARY KEY (id);


--
-- Name: expedientes_primer_contacto expedientes_primer_contacto_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.expedientes_primer_contacto
    ADD CONSTRAINT expedientes_primer_contacto_pkey PRIMARY KEY (id);


--
-- Name: notas_analisis notas_analisis_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.notas_analisis
    ADD CONSTRAINT notas_analisis_pkey PRIMARY KEY (id);


--
-- Name: notificaciones notificaciones_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.notificaciones
    ADD CONSTRAINT notificaciones_pkey PRIMARY KEY (id);


--
-- Name: oficios_informacion oficios_informacion_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.oficios_informacion
    ADD CONSTRAINT oficios_informacion_pkey PRIMARY KEY (id);


--
-- Name: personal_administrativo personal_administrativo_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.personal_administrativo
    ADD CONSTRAINT personal_administrativo_pkey PRIMARY KEY (id);


--
-- Name: plantillas_documentos plantillas_documentos_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.plantillas_documentos
    ADD CONSTRAINT plantillas_documentos_pkey PRIMARY KEY (id);


--
-- Name: preguntas_chatbot preguntas_chatbot_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.preguntas_chatbot
    ADD CONSTRAINT preguntas_chatbot_pkey PRIMARY KEY (id);


--
-- Name: queja_evidencias queja_evidencias_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.queja_evidencias
    ADD CONSTRAINT queja_evidencias_pkey PRIMARY KEY (id);


--
-- Name: queja_tutores queja_tutores_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.queja_tutores
    ADD CONSTRAINT queja_tutores_pkey PRIMARY KEY (id);


--
-- Name: quejas quejas_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.quejas
    ADD CONSTRAINT quejas_pkey PRIMARY KEY (id);


--
-- Name: recordatorios_urgencia recordatorios_urgencia_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.recordatorios_urgencia
    ADD CONSTRAINT recordatorios_urgencia_pkey PRIMARY KEY (id);


--
-- Name: remisiones_externas remisiones_externas_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.remisiones_externas
    ADD CONSTRAINT remisiones_externas_pkey PRIMARY KEY (id);


--
-- Name: respuestas_externas respuestas_externas_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.respuestas_externas
    ADD CONSTRAINT respuestas_externas_pkey PRIMARY KEY (id);


--
-- Name: usuarios uk1hecjqlapiwmdeojcgsu9g2sq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuarios
    ADD CONSTRAINT uk1hecjqlapiwmdeojcgsu9g2sq UNIQUE (correo_institucional);


--
-- Name: personal_administrativo uk2opqtyq0t7bhcmtdvmmv8xjgo; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.personal_administrativo
    ADD CONSTRAINT uk2opqtyq0t7bhcmtdvmmv8xjgo UNIQUE (numero_empleado);


--
-- Name: expedientes_investigacion uk4elac8d1a0gm04xxf27b2gyl4; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.expedientes_investigacion
    ADD CONSTRAINT uk4elac8d1a0gm04xxf27b2gyl4 UNIQUE (folio_origen);


--
-- Name: usuarios uk849fd4gs25xsaf49io4kj6oie; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuarios
    ADD CONSTRAINT uk849fd4gs25xsaf49io4kj6oie UNIQUE (boleta);


--
-- Name: expedientes_investigacion uk91bijjwwjr6csd5a0lod03vq9; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.expedientes_investigacion
    ADD CONSTRAINT uk91bijjwwjr6csd5a0lod03vq9 UNIQUE (folio);


--
-- Name: remisiones_externas uk9vcrx505omqggrc8lwys7jxws; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.remisiones_externas
    ADD CONSTRAINT uk9vcrx505omqggrc8lwys7jxws UNIQUE (folio);


--
-- Name: expedientes_primer_contacto uk_expediente_pc_folio; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.expedientes_primer_contacto
    ADD CONSTRAINT uk_expediente_pc_folio UNIQUE (folio);


--
-- Name: expedientes_primer_contacto uk_expediente_pc_folio_origen; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.expedientes_primer_contacto
    ADD CONSTRAINT uk_expediente_pc_folio_origen UNIQUE (folio_origen);


--
-- Name: dependencias ukafmof9iejhjaprek9yeqaygjn; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.dependencias
    ADD CONSTRAINT ukafmof9iejhjaprek9yeqaygjn UNIQUE (clave);


--
-- Name: queja_tutores ukbvl4dq2kgx1cagdd3you89i3c; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.queja_tutores
    ADD CONSTRAINT ukbvl4dq2kgx1cagdd3you89i3c UNIQUE (queja_id);


--
-- Name: acuerdos_conclusion ukccim75i3sfufb9qthxjofxpnh; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.acuerdos_conclusion
    ADD CONSTRAINT ukccim75i3sfufb9qthxjofxpnh UNIQUE (expediente_id);


--
-- Name: plantillas_documentos ukjvbf1vu29optx6ot41aw7wxip; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.plantillas_documentos
    ADD CONSTRAINT ukjvbf1vu29optx6ot41aw7wxip UNIQUE (tipo);


--
-- Name: personal_administrativo ukjxhy9dkd87q268rvmbg775rs2; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.personal_administrativo
    ADD CONSTRAINT ukjxhy9dkd87q268rvmbg775rs2 UNIQUE (correo_institucional);


--
-- Name: quejas ukp1ajrjo9em1239n7c7ywdt8da; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.quejas
    ADD CONSTRAINT ukp1ajrjo9em1239n7c7ywdt8da UNIQUE (folio_primer_contacto);


--
-- Name: expedientes_primer_contacto ukrjpg68hvp02ryr5y6a5lip64o; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.expedientes_primer_contacto
    ADD CONSTRAINT ukrjpg68hvp02ryr5y6a5lip64o UNIQUE (folio_subdefensoria);


--
-- Name: quejas uksvvmwncpvm37ehr33o23a6khw; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.quejas
    ADD CONSTRAINT uksvvmwncpvm37ehr33o23a6khw UNIQUE (numero_folio);


--
-- Name: usuarios usuarios_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuarios
    ADD CONSTRAINT usuarios_pkey PRIMARY KEY (id);


--
-- Name: queja_evidencias fkk4q23ik16etsees9fmbf2yhfk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.queja_evidencias
    ADD CONSTRAINT fkk4q23ik16etsees9fmbf2yhfk FOREIGN KEY (queja_id) REFERENCES public.quejas(id);


--
-- Name: queja_tutores fkpc85sbgtpsw6mw86mqrvpa6n7; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.queja_tutores
    ADD CONSTRAINT fkpc85sbgtpsw6mw86mqrvpa6n7 FOREIGN KEY (queja_id) REFERENCES public.quejas(id);


--
-- PostgreSQL database dump complete
--

\unrestrict 2IdUd2qjYWmW63fM2Jti6NTZ3tgLIlgfXRyZ8iTBY0ocf8Hl1Eb1ByT0cHXcT3R

