spring.application.name=primer-contacto-service
server.port=8082

# H2 temporal
spring.datasource.url=jdbc:h2:mem:primer_contacto_db
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Consola H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Backend central
plataforma.central.base-url=http://localhost:8080/api