server.port=8093
server.tomcat.threads.max=20
spring.application.name=antecedentes-service

ia.dataset.historico=Dataset/quejas_sinteticas.json
ia.dataset.nuevo=Dataset/quejas_prueba_30.json
ia.dataset.aprendidas=Dataset/quejas_aprendidas.json

ia.busqueda.umbral=0.25
ia.busqueda.top-k=5
ia.busqueda.top-k-maximo=50

ia.resumen.numero-oraciones=3
ia.resumen.numero-oraciones-maximo=20
ia.resumen.redundancia=0.60
