spring:
  application:
    name: login
  
  datasource:
    url: jdbc:postgresql://localhost:5432/defensoria_db
    username: bicho_admin
    password: escom2026
    driver-class-name: org.postgresql.Driver
  
  jpa:
    
    hibernate:
      ddl-auto: update
    show-sql: true
    
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
        
        hbm2ddl.import_files: import.sql

  
  sql:
    init:
      mode: always

server:
  port: 8081


logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE