-- Seed de catálogo de dependencias del IPN para queja-service
-- Generado a partir de dependencias_ipn.csv — correr una sola vez tras el primer
-- arranque del servicio con la nueva entidad Dependencia (Hibernate ddl-auto=update
-- ya habrá creado la tabla 'dependencias' vacía).

INSERT INTO dependencias (clave, clave_padre, nombre, abreviatura, tipo, categoria, nivel, pagina_manual, activo, notas, creado_en) VALUES
  ('DG', NULL, 'Dirección General', NULL, 'Dirección General', 'Órganos y Áreas de la Administración Central', 1, 10, TRUE, NULL, now()),
  ('DG.1', 'DG', 'Coordinación de Asesores', NULL, 'Coordinación', 'Órganos y Áreas de la Administración Central', 2, 11, TRUE, NULL, now()),
  ('DG.2', 'DG', 'Coordinación Administrativa', NULL, 'Coordinación', 'Órganos y Áreas de la Administración Central', 2, 12, TRUE, NULL, now()),
  ('DG.3', 'DG', 'Coordinación de Relaciones Públicas', NULL, 'Coordinación', 'Órganos y Áreas de la Administración Central', 2, 13, TRUE, NULL, now()),
  ('DG.4', 'DG', 'Coordinación de Comunicación Social', NULL, 'Coordinación', 'Órganos y Áreas de la Administración Central', 2, 14, TRUE, NULL, now()),
  ('DG.4.1', 'DG.4', 'División de Difusión', NULL, 'División', 'Órganos y Áreas de la Administración Central', 3, 15, TRUE, NULL, now()),
  ('DG.4.2', 'DG.4', 'División de Redacción', NULL, 'División', 'Órganos y Áreas de la Administración Central', 3, 16, TRUE, NULL, now()),
  ('SG', NULL, 'Secretaría General', NULL, 'Secretaría', 'Órganos y Áreas de la Administración Central', 1, 18, TRUE, NULL, now()),
  ('SG.1', 'SG', 'Coordinación de Asistencia Técnica', NULL, 'Coordinación', 'Órganos y Áreas de la Administración Central', 2, 20, TRUE, NULL, now()),
  ('SG.1.1', 'SG.1', 'División de Prevención', NULL, 'División', 'Órganos y Áreas de la Administración Central', 3, 21, TRUE, NULL, now()),
  ('SG.1.2', 'SG.1', 'División de Apoyo y Seguridad', NULL, 'División', 'Órganos y Áreas de la Administración Central', 3, 22, TRUE, NULL, now()),
  ('SG.1.3', 'SG.1', 'División Operación', NULL, 'División', 'Órganos y Áreas de la Administración Central', 3, 24, TRUE, NULL, now()),
  ('OAG', NULL, 'Oficina del Abogado General', NULL, 'Oficina', 'Órganos y Áreas de la Administración Central', 1, 27, TRUE, NULL, now()),
  ('OAG.1', 'OAG', 'Dirección de Asuntos Jurídicos', NULL, 'Dirección', 'Órganos y Áreas de la Administración Central', 2, 28, TRUE, NULL, now()),
  ('OAG.2', 'OAG', 'Dirección de Normatividad Consulta y Dictaminación', NULL, 'Dirección', 'Órganos y Áreas de la Administración Central', 2, 30, TRUE, NULL, now()),
  ('CNC', NULL, 'Centro Nacional de Cálculo', 'CENAC', 'Centro', 'Órganos y Áreas de la Administración Central', 1, 32, TRUE, NULL, now()),
  ('CNC.1', 'CNC', 'División de Ingeniería de Software y Administración de Bases de Datos', NULL, 'División', 'Órganos y Áreas de la Administración Central', 2, 33, TRUE, NULL, now()),
  ('CNC.2', 'CNC', 'División de Desarrollo de Sistemas', NULL, 'División', 'Órganos y Áreas de la Administración Central', 2, 34, TRUE, NULL, now()),
  ('PD', NULL, 'Presidencia del Decanato', NULL, 'Presidencia', 'Órganos y Áreas de la Administración Central', 1, 36, TRUE, NULL, now()),
  ('CGSI', NULL, 'Coordinación General de Servicios Informáticos', NULL, 'Coordinación', 'Órganos y Áreas de la Administración Central', 1, 38, TRUE, NULL, now()),
  ('CGSI.1', 'CGSI', 'Dirección de Cómputo y Comunicaciones', NULL, 'Dirección', 'Órganos y Áreas de la Administración Central', 2, 39, TRUE, NULL, now()),
  ('CGSI.1.1', 'CGSI.1', 'División de Cómputo', NULL, 'División', 'Órganos y Áreas de la Administración Central', 3, 40, TRUE, NULL, now()),
  ('CGSI.1.2', 'CGSI.1', 'División de Telecomunicaciones', NULL, 'División', 'Órganos y Áreas de la Administración Central', 3, 41, TRUE, NULL, now()),
  ('CGSI.1.3', 'CGSI.1', 'División de Servicios Técnicos', NULL, 'División', 'Órganos y Áreas de la Administración Central', 3, 42, TRUE, NULL, now()),
  ('CGSI.2', 'CGSI', 'Coordinación del Sistema Institucional de Información', NULL, 'Coordinación', 'Órganos y Áreas de la Administración Central', 2, 43, TRUE, NULL, now()),
  ('OIC', NULL, 'Órgano Interno de Control', NULL, 'Órgano', 'Órganos y Áreas de la Administración Central', 1, 45, TRUE, NULL, now()),
  ('OIC.1', 'OIC', 'Área de Auditoría para el Desarrollo y Mejora de la Gestión Pública', NULL, 'Área', 'Órganos y Áreas de la Administración Central', 2, 46, TRUE, NULL, now()),
  ('OIC.2', 'OIC', 'Área de Auditoría Interna a Áreas Centrales y Centros Federales', NULL, 'Área', 'Órganos y Áreas de la Administración Central', 2, 47, TRUE, NULL, now()),
  ('OIC.3', 'OIC', 'Área de Auditoría Interna a Unidades Académicas', NULL, 'Área', 'Órganos y Áreas de la Administración Central', 2, 48, TRUE, NULL, now()),
  ('OIC.4', 'OIC', 'Área de Quejas y Responsabilidades', NULL, 'Área', 'Órganos y Áreas de la Administración Central', 2, 49, TRUE, NULL, now()),
  ('UPGPG', NULL, 'Unidad Politécnica de Gestión con Perspectiva de Género', 'UPGPG', 'Unidad', 'Órganos y Áreas de la Administración Central', 1, 51, TRUE, NULL, now()),
  ('DDP', NULL, 'Defensoría de los Derechos Politécnicos', 'DDP', 'Dependencia', 'Órganos y Áreas de la Administración Central', 1, 53, TRUE, NULL, now()),
  ('SA', NULL, 'Secretaría Académica', NULL, 'Secretaría', 'Órganos y Áreas de la Administración Central', 1, 55, TRUE, NULL, now()),
  ('SA.1', 'SA', 'Dirección de Educación Media Superior', NULL, 'Dirección', 'Órganos y Áreas de la Administración Central', 2, 58, TRUE, NULL, now()),
  ('SA.1.1', 'SA.1', 'División de Procesos Formativos', NULL, 'División', 'Órganos y Áreas de la Administración Central', 3, 59, TRUE, NULL, now()),
  ('SA.1.2', 'SA.1', 'División de Innovación Académica', NULL, 'División', 'Órganos y Áreas de la Administración Central', 3, 60, TRUE, NULL, now()),
  ('SA.1.3', 'SA.1', 'División de Gestión y Calidad Educativa', NULL, 'División', 'Órganos y Áreas de la Administración Central', 3, 61, TRUE, NULL, now()),
  ('SA.2', 'SA', 'Dirección de Educación Superior', NULL, 'Dirección', 'Órganos y Áreas de la Administración Central', 2, 62, TRUE, NULL, now()),
  ('SA.2.1', 'SA.2', 'División de Procesos Formativos', NULL, 'División', 'Órganos y Áreas de la Administración Central', 3, 63, TRUE, NULL, now()),
  ('SA.2.2', 'SA.2', 'División de Innovación Académica', NULL, 'División', 'Órganos y Áreas de la Administración Central', 3, 64, TRUE, NULL, now()),
  ('SA.2.3', 'SA.2', 'División de Gestión y Calidad Educativa', NULL, 'División', 'Órganos y Áreas de la Administración Central', 3, 65, TRUE, NULL, now()),
  ('SA.2.4', 'SA.2', 'División de Operación de Unidades Académicas', NULL, 'División', 'Órganos y Áreas de la Administración Central', 3, 66, TRUE, NULL, now()),
  ('SA.3', 'SA', 'Dirección de Formación en Lenguas Extranjeras', NULL, 'Dirección', 'Órganos y Áreas de la Administración Central', 2, 67, TRUE, NULL, now()),
  ('SIP', NULL, 'Secretaría de Investigación y Posgrado', NULL, 'Secretaría', 'Órganos y Áreas de la Administración Central', 1, 69, TRUE, NULL, now()),
  ('SIP.1', 'SIP', 'Dirección de Posgrado', NULL, 'Dirección', 'Órganos y Áreas de la Administración Central', 2, 70, TRUE, NULL, now()),
  ('SIP.1.1', 'SIP.1', 'División de Operación y Promoción del Posgrado', NULL, 'División', 'Órganos y Áreas de la Administración Central', 3, 71, TRUE, NULL, now()),
  ('SIP.2', 'SIP', 'Dirección de Apoyo al Posgrado', NULL, 'Dirección', 'Órganos y Áreas de la Administración Central', 2, 72, TRUE, NULL, now()),
  ('SIP.2.1', 'SIP.2', 'División de Apoyo a Programas en Ambientes Virtuales', NULL, 'División', 'Órganos y Áreas de la Administración Central', 3, 73, TRUE, NULL, now()),
  ('SIP.3', 'SIP', 'Dirección de Investigación', NULL, 'Dirección', 'Órganos y Áreas de la Administración Central', 2, 74, TRUE, NULL, now()),
  ('SIP.3.1', 'SIP.3', 'División de Operación y Promoción a la Investigación', NULL, 'División', 'Órganos y Áreas de la Administración Central', 3, 75, TRUE, NULL, now()),
  ('SIP.3.2', 'SIP.3', 'División de Apoyo a la Investigación', NULL, 'División', 'Órganos y Áreas de la Administración Central', 3, 76, TRUE, NULL, now()),
  ('SSE', NULL, 'Secretaría de Servicios Educativos', NULL, 'Secretaría', 'Órganos y Áreas de la Administración Central', 1, 78, TRUE, NULL, now()),
  ('SSE.1', 'SSE', 'Dirección de Administración Escolar', NULL, 'Dirección', 'Órganos y Áreas de la Administración Central', 2, 80, TRUE, NULL, now()),
  ('SSE.1.1', 'SSE.1', 'División de Admisión y Control Escolar', NULL, 'División', 'Órganos y Áreas de la Administración Central', 3, 81, TRUE, NULL, now()),
  ('SSE.1.2', 'SSE.1', 'División de Registro y Certificación de Estudios', NULL, 'División', 'Órganos y Áreas de la Administración Central', 3, 83, TRUE, NULL, now()),
  ('SSE.2', 'SSE', 'Dirección de Servicios Estudiantiles', NULL, 'Dirección', 'Órganos y Áreas de la Administración Central', 2, 84, TRUE, NULL, now()),
  ('SSE.2.1', 'SSE.2', 'División de Prestaciones Sociales y Atención a la Salud', NULL, 'División', 'Órganos y Áreas de la Administración Central', 3, 85, TRUE, NULL, now()),
  ('SSE.2.2', 'SSE.2', 'División de Apoyo y Servicios a Estudiantes', NULL, 'División', 'Órganos y Áreas de la Administración Central', 3, 87, TRUE, NULL, now()),
  ('SSE.3', 'SSE', 'Dirección de Bibliotecas', NULL, 'Dirección', 'Órganos y Áreas de la Administración Central', 2, 89, TRUE, NULL, now()),
  ('SSE.3.1', 'SSE.3', 'División de Servicios Bibliotecarios', NULL, 'División', 'Órganos y Áreas de la Administración Central', 3, 90, TRUE, NULL, now()),
  ('SSE.3.2', 'SSE.3', 'División de Información y Documentación', NULL, 'División', 'Órganos y Áreas de la Administración Central', 3, 91, TRUE, NULL, now()),
  ('SSE.4', 'SSE', 'Dirección de Difusión y Fomento a la Cultura', NULL, 'Dirección', 'Órganos y Áreas de la Administración Central', 2, 92, TRUE, NULL, now()),
  ('SSE.4.1', 'SSE.4', 'División de Fomento y Promoción Cultural', NULL, 'División', 'Órganos y Áreas de la Administración Central', 3, 94, TRUE, NULL, now()),
  ('SSE.4.2', 'SSE.4', 'División de Difusión', NULL, 'División', 'Órganos y Áreas de la Administración Central', 3, 95, TRUE, NULL, now()),
  ('SSE.5', 'SSE', 'Dirección de Desarrollo y Fomento Deportivo', NULL, 'Dirección', 'Órganos y Áreas de la Administración Central', 2, 96, TRUE, NULL, now()),
  ('SSE.5.1', 'SSE.5', 'División de Fomento Deportivo', NULL, 'División', 'Órganos y Áreas de la Administración Central', 3, 97, TRUE, NULL, now()),
  ('SSE.5.2', 'SSE.5', 'División de Desarrollo Deportivo', NULL, 'División', 'Órganos y Áreas de la Administración Central', 3, 98, TRUE, NULL, now()),
  ('SEIS', NULL, 'Secretaría de Extensión e Integración Social', NULL, 'Secretaría', 'Órganos y Áreas de la Administración Central', 1, 100, TRUE, NULL, now()),
  ('SEIS.1', 'SEIS', 'Dirección de Egresados y Servicio Social', NULL, 'Dirección', 'Órganos y Áreas de la Administración Central', 2, 102, TRUE, NULL, now()),
  ('SEIS.1.1', 'SEIS.1', 'División de Servicio Social', NULL, 'División', 'Órganos y Áreas de la Administración Central', 3, 103, TRUE, NULL, now()),
  ('SEIS.1.2', 'SEIS.1', 'División de Egresados', NULL, 'División', 'Órganos y Áreas de la Administración Central', 3, 104, TRUE, NULL, now()),
  ('SEIS.2', 'SEIS', 'Dirección de Publicaciones', NULL, 'Dirección', 'Órganos y Áreas de la Administración Central', 2, 105, TRUE, NULL, now()),
  ('SEIS.2.1', 'SEIS.2', 'División Editorial', NULL, 'División', 'Órganos y Áreas de la Administración Central', 3, 106, TRUE, NULL, now()),
  ('SEIS.2.2', 'SEIS.2', 'División de Comercialización de la Obra Editorial', NULL, 'División', 'Órganos y Áreas de la Administración Central', 3, 109, TRUE, NULL, now()),
  ('SEIS.3', 'SEIS', 'Dirección de Educación Continua', NULL, 'Dirección', 'Órganos y Áreas de la Administración Central', 2, 110, TRUE, NULL, now()),
  ('SEIS.3.1', 'SEIS.3', 'División de Programas de Educación Continua', NULL, 'División', 'Órganos y Áreas de la Administración Central', 3, 111, TRUE, NULL, now()),
  ('SEIS.3.2', 'SEIS.3', 'División de Operación de Centros de Educación Continua', NULL, 'División', 'Órganos y Áreas de la Administración Central', 3, 112, TRUE, NULL, now()),
  ('SEIS.4', 'SEIS', 'Coordinación de Cooperación Académica', NULL, 'Coordinación', 'Órganos y Áreas de la Administración Central', 2, 113, TRUE, NULL, now()),
  ('SEIS.4.1', 'SEIS.4', 'División de Gestión de la Cooperación', NULL, 'División', 'Órganos y Áreas de la Administración Central', 3, 114, TRUE, NULL, now()),
  ('SEIS.4.2', 'SEIS.4', 'División de Relaciones Nacionales e Internacionales', NULL, 'División', 'Órganos y Áreas de la Administración Central', 3, 115, TRUE, NULL, now()),
  ('SGE', NULL, 'Secretaría de Gestión Estratégica', NULL, 'Secretaría', 'Órganos y Áreas de la Administración Central', 1, 117, TRUE, NULL, now()),
  ('SGE.1', 'SGE', 'Dirección de Planeación', NULL, 'Dirección', 'Órganos y Áreas de la Administración Central', 2, 118, TRUE, NULL, now()),
  ('SGE.1.1', 'SGE.1', 'División de Planeación y Prospectiva', NULL, 'División', 'Órganos y Áreas de la Administración Central', 3, 119, TRUE, NULL, now()),
  ('SGE.1.2', 'SGE.1', 'División de Estudios y Proyectos', NULL, 'División', 'Órganos y Áreas de la Administración Central', 3, 120, TRUE, NULL, now()),
  ('SGE.2', 'SGE', 'Dirección de Evaluación', NULL, 'Dirección', 'Órganos y Áreas de la Administración Central', 2, 121, TRUE, NULL, now()),
  ('SGE.2.1', 'SGE.2', 'División de Evaluación', NULL, 'División', 'Órganos y Áreas de la Administración Central', 3, 122, TRUE, NULL, now()),
  ('SGE.2.2', 'SGE.2', 'División de Información', NULL, 'División', 'Órganos y Áreas de la Administración Central', 3, 123, TRUE, NULL, now()),
  ('SGE.3', 'SGE', 'Dirección de Programación y Presupuesto', NULL, 'Dirección', 'Órganos y Áreas de la Administración Central', 2, 124, TRUE, NULL, now()),
  ('SGE.3.1', 'SGE.3', 'División de Programación', NULL, 'División', 'Órganos y Áreas de la Administración Central', 3, 125, TRUE, NULL, now()),
  ('SGE.3.2', 'SGE.3', 'División de Presupuesto', NULL, 'División', 'Órganos y Áreas de la Administración Central', 3, 126, TRUE, NULL, now()),
  ('SAD', NULL, 'Secretaría de Administración', NULL, 'Secretaría', 'Órganos y Áreas de la Administración Central', 1, 128, TRUE, NULL, now()),
  ('SAD.1', 'SAD', 'Dirección de Capital Humano', NULL, 'Dirección', 'Órganos y Áreas de la Administración Central', 2, 130, TRUE, NULL, now()),
  ('SAD.1.1', 'SAD.1', 'División de Admisión y Desarrollo del Personal', NULL, 'División', 'Órganos y Áreas de la Administración Central', 3, 131, TRUE, NULL, now()),
  ('SAD.1.2', 'SAD.1', 'División de Trayectorias del Personal', NULL, 'División', 'Órganos y Áreas de la Administración Central', 3, 132, TRUE, NULL, now()),
  ('SAD.1.3', 'SAD.1', 'División de Sistemas de Información', NULL, 'División', 'Órganos y Áreas de la Administración Central', 3, 134, TRUE, NULL, now()),
  ('SAD.1.4', 'SAD.1', 'División de Remuneraciones', NULL, 'División', 'Órganos y Áreas de la Administración Central', 3, 135, TRUE, NULL, now()),
  ('SAD.2', 'SAD', 'Dirección de Recursos Financieros', NULL, 'Dirección', 'Órganos y Áreas de la Administración Central', 2, 136, TRUE, NULL, now()),
  ('SAD.2.1', 'SAD.2', 'División de Control y Ejercicio del Presupuesto', NULL, 'División', 'Órganos y Áreas de la Administración Central', 3, 137, TRUE, NULL, now()),
  ('SAD.2.2', 'SAD.2', 'División de Contabilidad', NULL, 'División', 'Órganos y Áreas de la Administración Central', 3, 138, TRUE, NULL, now()),
  ('SAD.3', 'SAD', 'Dirección de Recursos Materiales y Servicios', NULL, 'Dirección', 'Órganos y Áreas de la Administración Central', 2, 139, TRUE, NULL, now()),
  ('SAD.3.1', 'SAD.3', 'División de Adquisiciones de Bienes y Servicios', NULL, 'División', 'Órganos y Áreas de la Administración Central', 3, 140, TRUE, NULL, now()),
  ('SAD.3.2', 'SAD.3', 'División de Infraestructura Física', NULL, 'División', 'Órganos y Áreas de la Administración Central', 3, 141, TRUE, NULL, now()),
  ('SAD.3.3', 'SAD.3', 'División Servicios Generales', NULL, 'División', 'Órganos y Áreas de la Administración Central', 3, 143, TRUE, NULL, now()),
  ('CCDI', NULL, 'Coordinación de Centros de Desarrollo Infantil', NULL, 'Coordinación', 'Órganos y Áreas de la Administración Central', 1, 145, TRUE, NULL, now()),
  ('CCDI.1', 'CCDI', 'Centro de Desarrollo Infantil "Laura Pérez de Baíz"', NULL, 'Centro', 'Órganos y Áreas de la Administración Central', 2, 146, TRUE, NULL, now()),
  ('CCDI.2', 'CCDI', 'Centro de Desarrollo Infantil "Amalia Solórzano de Cárdenas"', NULL, 'Centro', 'Órganos y Áreas de la Administración Central', 2, 147, TRUE, NULL, now()),
  ('CCDI.3', 'CCDI', 'Centro de Desarrollo Infantil "Eva Sámano de López Mateos"', NULL, 'Centro', 'Órganos y Áreas de la Administración Central', 2, 148, TRUE, NULL, now()),
  ('CCDI.4', 'CCDI', 'Centro de Desarrollo Infantil "Clementina Batalla de Bassols"', NULL, 'Centro', 'Órganos y Áreas de la Administración Central', 2, 149, TRUE, NULL, now()),
  ('CCDI.5', 'CCDI', 'Centro de Desarrollo Infantil "Margarita Salazar de Ero"', NULL, 'Centro', 'Órganos y Áreas de la Administración Central', 2, 150, TRUE, NULL, now()),
  ('CCDI.6', 'CCDI', 'Centro de Desarrollo Infantil "Zacatenco"', NULL, 'Centro', 'Órganos y Áreas de la Administración Central', 2, 151, TRUE, NULL, now()),
  ('CECYT1', NULL, 'CECyT No. 1 "Gonzalo Vázquez Vela"', 'CECyT 1', 'Unidad Académica', 'Unidades Académicas de Nivel Medio Superior, Rama de Ingeniería y Ciencias Físico Matemáticas', 1, 153, TRUE, NULL, now()),
  ('CECYT2', NULL, 'CECyT No. 2 "Miguel Bernard"', 'CECyT 2', 'Unidad Académica', 'Unidades Académicas de Nivel Medio Superior, Rama de Ingeniería y Ciencias Físico Matemáticas', 1, 154, TRUE, NULL, now()),
  ('CECYT3', NULL, 'CECyT No. 3 "Estanislao Ramírez Ruiz"', 'CECyT 3', 'Unidad Académica', 'Unidades Académicas de Nivel Medio Superior, Rama de Ingeniería y Ciencias Físico Matemáticas', 1, 155, TRUE, NULL, now()),
  ('CECYT4', NULL, 'CECyT No. 4 "Lázaro Cárdenas"', 'CECyT 4', 'Unidad Académica', 'Unidades Académicas de Nivel Medio Superior, Rama de Ingeniería y Ciencias Físico Matemáticas', 1, 156, TRUE, NULL, now()),
  ('CECYT7', NULL, 'CECyT No. 7 "Cuauhtémoc"', 'CECyT 7', 'Unidad Académica', 'Unidades Académicas de Nivel Medio Superior, Rama de Ingeniería y Ciencias Físico Matemáticas', 1, 157, TRUE, NULL, now()),
  ('CECYT8', NULL, 'CECyT No. 8 "Narciso Bassols"', 'CECyT 8', 'Unidad Académica', 'Unidades Académicas de Nivel Medio Superior, Rama de Ingeniería y Ciencias Físico Matemáticas', 1, 158, TRUE, NULL, now()),
  ('CECYT9', NULL, 'CECyT No. 9 "Juan de Dios Bátiz"', 'CECyT 9', 'Unidad Académica', 'Unidades Académicas de Nivel Medio Superior, Rama de Ingeniería y Ciencias Físico Matemáticas', 1, 159, TRUE, NULL, now()),
  ('CECYT10', NULL, 'CECyT No. 10 "Carlos Vallejo Márquez"', 'CECyT 10', 'Unidad Académica', 'Unidades Académicas de Nivel Medio Superior, Rama de Ingeniería y Ciencias Físico Matemáticas', 1, 160, TRUE, NULL, now()),
  ('CECYT11', NULL, 'CECyT No. 11 "Alfredo Massieu"', 'CECyT 11', 'Unidad Académica', 'Unidades Académicas de Nivel Medio Superior, Rama de Ingeniería y Ciencias Físico Matemáticas', 1, 161, TRUE, NULL, now()),
  ('CET1', NULL, 'CET No. 1 "Walter Cross Buchanan"', 'CET 1', 'Unidad Académica', 'Unidades Académicas de Nivel Medio Superior, Rama de Ingeniería y Ciencias Físico Matemáticas', 1, 162, TRUE, NULL, now()),
  ('CECYT6', NULL, 'CECyT No. 6 "Miguel Othón de Mendizábal"', 'CECyT 6', 'Unidad Académica', 'Unidades Académicas de Nivel Medio Superior, Rama de Ciencias Médico Biológicas', 1, 164, TRUE, NULL, now()),
  ('CECYT15', NULL, 'CECyT No. 15 "Diódoro Antúnez Echegaray"', 'CECyT 15', 'Unidad Académica', 'Unidades Académicas de Nivel Medio Superior, Rama de Ciencias Médico Biológicas', 1, 165, TRUE, NULL, now()),
  ('CECYT5', NULL, 'CECyT No. 5 "Benito Juárez"', 'CECyT 5', 'Unidad Académica', 'Unidades Académicas de Nivel Medio Superior, Rama de Ciencias Sociales y Administrativas', 1, 167, TRUE, 'Categoría de rama inferida, no visible con claridad en el escaneo original', now()),
  ('CECYT12', NULL, 'CECyT No. 12 "José María Morelos"', 'CECyT 12', 'Unidad Académica', 'Unidades Académicas de Nivel Medio Superior, Rama de Ciencias Sociales y Administrativas', 1, 168, TRUE, 'Categoría de rama inferida, no visible con claridad en el escaneo original', now()),
  ('CECYT13', NULL, 'CECyT No. 13 "Ricardo Flores Magón"', 'CECyT 13', 'Unidad Académica', 'Unidades Académicas de Nivel Medio Superior, Rama de Ciencias Sociales y Administrativas', 1, 169, TRUE, 'Categoría de rama inferida, no visible con claridad en el escaneo original', now()),
  ('CECYT14', NULL, 'CECyT No. 14 "Luis Enrique Erro"', 'CECyT 14', 'Unidad Académica', 'Unidades Académicas de Nivel Medio Superior, Rama de Ciencias Sociales y Administrativas', 1, 170, TRUE, 'Categoría de rama inferida, no visible con claridad en el escaneo original', now()),
  ('CECYT16', NULL, 'CECyT No. 16 "Hidalgo"', 'CECyT 16', 'Unidad Académica', 'Unidades Académicas de Nivel Medio Superior Interdisciplinarias', 1, 172, TRUE, NULL, now()),
  ('CECYT17', NULL, 'CECyT No. 17 "León, Guanajuato"', 'CECyT 17', 'Unidad Académica', 'Unidades Académicas de Nivel Medio Superior Interdisciplinarias', 1, 173, TRUE, NULL, now()),
  ('CECYT18', NULL, 'CECyT No. 18 "Zacatecas"', 'CECyT 18', 'Unidad Académica', 'Unidades Académicas de Nivel Medio Superior Interdisciplinarias', 1, NULL, TRUE, 'Plantel de nueva creación (2025/2026); no aparece en el manual de organización vigente. Sitio: https://cecyt18.ipn.mx/', now()),
  ('CECYT19', NULL, 'CECyT No. 19 "Leona Vicario"', 'CECyT 19', 'Unidad Académica', 'Unidades Académicas de Nivel Medio Superior Interdisciplinarias', 1, NULL, TRUE, 'Plantel de nueva creación (2025/2026); no aparece en el manual de organización vigente. Sitio: https://cecyt19.ipn.mx/', now()),
  ('ESIME-ZAC', NULL, 'Escuela Superior de Ingeniería Mecánica y Eléctrica, Unidad Zacatenco', 'ESIME Zacatenco', 'Unidad Académica', 'Unidades Académicas de Nivel Superior, Rama de Ingeniería y Ciencias Físico Matemáticas', 1, 175, TRUE, NULL, now()),
  ('ESIME-CUL', NULL, 'Escuela Superior de Ingeniería Mecánica y Eléctrica, Unidad Culhuacán', 'ESIME Culhuacán', 'Unidad Académica', 'Unidades Académicas de Nivel Superior, Rama de Ingeniería y Ciencias Físico Matemáticas', 1, 176, TRUE, NULL, now()),
  ('ESIME-AZC', NULL, 'Escuela Superior de Ingeniería Mecánica y Eléctrica, Unidad Azcapotzalco', 'ESIME Azcapotzalco', 'Unidad Académica', 'Unidades Académicas de Nivel Superior, Rama de Ingeniería y Ciencias Físico Matemáticas', 1, 177, TRUE, NULL, now()),
  ('ESIME-TIC', NULL, 'Escuela Superior de Ingeniería Mecánica y Eléctrica, Unidad Ticomán', 'ESIME Ticomán', 'Unidad Académica', 'Unidades Académicas de Nivel Superior, Rama de Ingeniería y Ciencias Físico Matemáticas', 1, 178, TRUE, NULL, now()),
  ('ESIA-ZAC', NULL, 'Escuela Superior de Ingeniería y Arquitectura, Unidad Zacatenco', 'ESIA Zacatenco', 'Unidad Académica', 'Unidades Académicas de Nivel Superior, Rama de Ingeniería y Ciencias Físico Matemáticas', 1, 179, TRUE, NULL, now()),
  ('ESIA-TEC', NULL, 'Escuela Superior de Ingeniería y Arquitectura, Unidad Tecamachalco', 'ESIA Tecamachalco', 'Unidad Académica', 'Unidades Académicas de Nivel Superior, Rama de Ingeniería y Ciencias Físico Matemáticas', 1, 180, TRUE, NULL, now()),
  ('ESIA-TIC', NULL, 'Escuela Superior de Ingeniería y Arquitectura, Unidad Ticomán', 'ESIA Ticomán', 'Unidad Académica', 'Unidades Académicas de Nivel Superior, Rama de Ingeniería y Ciencias Físico Matemáticas', 1, 181, TRUE, NULL, now()),
  ('ESIT', NULL, 'Escuela Superior de Ingeniería Textil', 'ESIT', 'Unidad Académica', 'Unidades Académicas de Nivel Superior, Rama de Ingeniería y Ciencias Físico Matemáticas', 1, 182, TRUE, NULL, now()),
  ('ESFM', NULL, 'Escuela Superior de Física y Matemáticas', 'ESFM', 'Unidad Académica', 'Unidades Académicas de Nivel Superior, Rama de Ingeniería y Ciencias Físico Matemáticas', 1, 183, TRUE, NULL, now()),
  ('ESCOM', NULL, 'Escuela Superior de Cómputo', 'ESCOM', 'Unidad Académica', 'Unidades Académicas de Nivel Superior, Rama de Ingeniería y Ciencias Físico Matemáticas', 1, 184, TRUE, NULL, now()),
  ('UPIICSA', NULL, 'Unidad Profesional Interdisciplinaria de Ingeniería y Ciencias Sociales y Administrativas', 'UPIICSA', 'Unidad Académica', 'Unidades Académicas de Nivel Superior, Rama de Ingeniería y Ciencias Físico Matemáticas', 1, 186, TRUE, NULL, now()),
  ('UPIITA', NULL, 'Unidad Profesional Interdisciplinaria de Ingeniería y Tecnologías Avanzadas', 'UPIITA', 'Unidad Académica', 'Unidades Académicas de Nivel Superior, Rama de Ingeniería y Ciencias Físico Matemáticas', 1, 187, TRUE, NULL, now()),
  ('UPIBI', NULL, 'Unidad Profesional Interdisciplinaria de Biotecnología', 'UPIBI', 'Unidad Académica', 'Unidades Académicas de Nivel Superior, Rama de Ingeniería y Ciencias Físico Matemáticas', 1, 188, TRUE, NULL, now()),
  ('UPIG', NULL, 'Unidad Profesional Interdisciplinaria de Ingeniería, Campus Guanajuato', 'UPIG', 'Unidad Académica', 'Unidades Académicas de Nivel Superior, Rama de Ingeniería y Ciencias Físico Matemáticas', 1, 189, TRUE, NULL, now()),
  ('UPIZ', NULL, 'Unidad Profesional Interdisciplinaria de Ingeniería, Campus Zacatecas', 'UPIZ', 'Unidad Académica', 'Unidades Académicas de Nivel Superior, Rama de Ingeniería y Ciencias Físico Matemáticas', 1, 190, TRUE, NULL, now()),
  ('ENCB', NULL, 'Escuela Nacional de Ciencias Biológicas', 'ENCB', 'Unidad Académica', 'Unidades Académicas de Nivel Superior, Rama de Ciencias Médico Biológicas', 1, 193, TRUE, NULL, now()),
  ('ESM', NULL, 'Escuela Superior de Medicina', 'ESM', 'Unidad Académica', 'Unidades Académicas de Nivel Superior, Rama de Ciencias Médico Biológicas', 1, 194, TRUE, NULL, now()),
  ('ENMH', NULL, 'Escuela Nacional de Medicina y Homeopatía', 'ENMH', 'Unidad Académica', 'Unidades Académicas de Nivel Superior, Rama de Ciencias Médico Biológicas', 1, 195, TRUE, NULL, now()),
  ('ESEO', NULL, 'Escuela Superior de Enfermería y Obstetricia', 'ESEO', 'Unidad Académica', 'Unidades Académicas de Nivel Superior, Rama de Ciencias Médico Biológicas', 1, 196, TRUE, NULL, now()),
  ('CICS-MA', NULL, 'Centro Interdisciplinario de Ciencias de la Salud, Unidad Milpa Alta', 'CICS Milpa Alta', 'Unidad Académica', 'Unidades Académicas de Nivel Superior, Rama de Ciencias Médico Biológicas', 1, 196, TRUE, NULL, now()),
  ('CICS-ST', NULL, 'Centro Interdisciplinario de Ciencias de la Salud, Unidad Santo Tomás', 'CICS Santo Tomás', 'Unidad Académica', 'Unidades Académicas de Nivel Superior, Rama de Ciencias Médico Biológicas', 1, 197, TRUE, NULL, now()),
  ('ESCA-ST', NULL, 'Escuela Superior de Comercio y Administración, Unidad Santo Tomás', 'ESCA Santo Tomás', 'Unidad Académica', 'Unidades Académicas de Nivel Superior, Rama de Ingeniería y Ciencias Sociales y Administrativas', 1, 199, TRUE, NULL, now()),
  ('ESCA-TEP', NULL, 'Escuela Superior de Comercio y Administración, Unidad Tepepan', 'ESCA Tepepan', 'Unidad Académica', 'Unidades Académicas de Nivel Superior, Rama de Ingeniería y Ciencias Sociales y Administrativas', 1, 200, TRUE, NULL, now()),
  ('ESE', NULL, 'Escuela Superior de Economía', 'ESE', 'Unidad Académica', 'Unidades Académicas de Nivel Superior, Rama de Ingeniería y Ciencias Sociales y Administrativas', 1, 201, TRUE, NULL, now()),
  ('EST', NULL, 'Escuela Superior de Turismo', 'EST', 'Unidad Académica', 'Unidades Académicas de Nivel Superior, Rama de Ingeniería y Ciencias Sociales y Administrativas', 1, 202, TRUE, NULL, now()),
  ('CEPROBI', NULL, 'Centro de Desarrollo de Productos Bióticos', 'CEPROBI', 'Centro', 'Unidades Académicas de Investigación Científica y Tecnológica', 1, 204, TRUE, NULL, now()),
  ('CICIMAR', NULL, 'Centro Interdisciplinario de Ciencias Marinas', 'CICIMAR', 'Centro', 'Unidades Académicas de Investigación Científica y Tecnológica', 1, 205, TRUE, NULL, now()),
  ('CIIDIR-DGO', NULL, 'Centro Interdisciplinario de Investigación para el Desarrollo Integral Regional, Unidad Durango', 'CIIDIR Durango', 'Centro', 'Unidades Académicas de Investigación Científica y Tecnológica', 1, 206, TRUE, NULL, now()),
  ('CIIDIR-MICH', NULL, 'Centro Interdisciplinario de Investigación para el Desarrollo Integral Regional, Unidad Michoacán', 'CIIDIR Michoacán', 'Centro', 'Unidades Académicas de Investigación Científica y Tecnológica', 1, 207, TRUE, NULL, now()),
  ('CIIDIR-OAX', NULL, 'Centro Interdisciplinario de Investigación para el Desarrollo Integral Regional, Unidad Oaxaca', 'CIIDIR Oaxaca', 'Centro', 'Unidades Académicas de Investigación Científica y Tecnológica', 1, 208, TRUE, NULL, now()),
  ('CIIDIR-SIN', NULL, 'Centro Interdisciplinario de Investigación para el Desarrollo Integral Regional, Unidad Sinaloa', 'CIIDIR Sinaloa', 'Centro', 'Unidades Académicas de Investigación Científica y Tecnológica', 1, 209, TRUE, NULL, now()),
  ('CIIEMAD', NULL, 'Centro Interdisciplinario de Investigaciones y Estudios sobre Medio Ambiente y Desarrollo', 'CIIEMAD', 'Centro', 'Unidades Académicas de Investigación Científica y Tecnológica', 1, 210, TRUE, NULL, now()),
  ('CIC', NULL, 'Centro de Investigación en Computación', 'CIC', 'Centro', 'Unidades Académicas de Investigación Científica y Tecnológica', 1, 211, TRUE, NULL, now()),
  ('CIECAS', NULL, 'Centro de Investigaciones Económicas, Administrativas y Sociales', 'CIECAS', 'Centro', 'Unidades Académicas de Investigación Científica y Tecnológica', 1, 212, TRUE, NULL, now()),
  ('CBG', NULL, 'Centro de Biotecnología Genómica', 'CBG', 'Centro', 'Unidades Académicas de Investigación Científica y Tecnológica', 1, 213, TRUE, NULL, now()),
  ('CICATA-LEG', NULL, 'Centro de Investigación en Ciencia Aplicada y Tecnología Avanzada, Unidad Legaria', 'CICATA Legaria', 'Centro', 'Unidades Académicas de Investigación Científica y Tecnológica', 1, 214, TRUE, NULL, now()),
  ('CICATA-QRO', NULL, 'Centro de Investigación en Ciencia Aplicada y Tecnología Avanzada, Unidad Querétaro', 'CICATA Querétaro', 'Centro', 'Unidades Académicas de Investigación Científica y Tecnológica', 1, 215, TRUE, NULL, now()),
  ('CICATA-ALT', NULL, 'Centro de Investigación en Ciencia Aplicada y Tecnología Avanzada, Unidad Altamira', 'CICATA Altamira', 'Centro', 'Unidades Académicas de Investigación Científica y Tecnológica', 1, 216, TRUE, NULL, now()),
  ('CICATA-MOR', NULL, 'Centro de Investigación en Ciencia Aplicada y Tecnología Avanzada, Unidad Morelos', 'CICATA Morelos', 'Centro', 'Unidades Académicas de Investigación Científica y Tecnológica', 1, 217, TRUE, NULL, now()),
  ('CIBA', NULL, 'Centro de Investigación en Biotecnología Aplicada, Unidad Allende', 'CIBA', 'Centro', 'Unidades Académicas de Investigación Científica y Tecnológica', 1, 218, TRUE, NULL, now()),
  ('CITEDI', NULL, 'Centro de Investigación y Desarrollo Tecnológico en Cómputo', 'CITEDI', 'Centro', 'Unidades Académicas de Investigación Científica y Tecnológica', 1, 219, TRUE, NULL, now()),
  ('CIDETEC', NULL, 'Centro de Innovación y Desarrollo Tecnológico en Cómputo', 'CIDETEC', 'Centro', 'Unidades Académicas de Investigación Científica y Tecnológica', 1, 220, TRUE, NULL, now()),
  ('CIITEC', NULL, 'Centro de Investigación e Innovación Tecnológica', 'CIITEC', 'Centro', 'Unidades Académicas de Investigación Científica y Tecnológica', 1, 221, TRUE, NULL, now()),
  ('CMPMASL', NULL, 'Centro Mexicano para la Producción Más Limpia', 'CMP+L', 'Centro', 'Unidades Académicas de Investigación Científica y Tecnológica', 1, 222, TRUE, NULL, now()),
  ('CRPMASL-TAB', NULL, 'Centro Regional para la Producción Más Limpia, Unidad Tabasco', 'CRP+L Tabasco', 'Centro', 'Unidades Académicas de Investigación Científica y Tecnológica', 1, 223, TRUE, NULL, now()),
  ('CEC-ALL', NULL, 'Centro de Educación Continua, Unidad Allende', 'CEC Allende', 'Centro', 'Unidades Académicas de Educación Continua', 1, 225, TRUE, NULL, now()),
  ('CEC-CAJ', NULL, 'Centro de Educación Continua, Unidad Cajeme Sonora', 'CEC Cajeme Sonora', 'Centro', 'Unidades Académicas de Educación Continua', 1, 226, TRUE, NULL, now()),
  ('CEC-CAM', NULL, 'Centro de Educación Continua, Unidad Campeche', 'CEC Campeche', 'Centro', 'Unidades Académicas de Educación Continua', 1, 227, TRUE, NULL, now()),
  ('CEC-CAN', NULL, 'Centro de Educación Continua, Unidad Cancún', 'CEC Cancún', 'Centro', 'Unidades Académicas de Educación Continua', 1, 228, TRUE, NULL, now()),
  ('CEC-CUL', NULL, 'Centro de Educación Continua, Unidad Culiacán', 'CEC Culiacán', 'Centro', 'Unidades Académicas de Educación Continua', 1, 229, TRUE, NULL, now()),
  ('CEC-DGO', NULL, 'Centro de Educación Continua, Unidad Durango', 'CEC Durango', 'Centro', 'Unidades Académicas de Educación Continua', 1, 230, TRUE, NULL, now()),
  ('CEC-HGO', NULL, 'Centro de Educación Continua, Unidad Hidalgo', 'CEC Hidalgo', 'Centro', 'Unidades Académicas de Educación Continua', 1, 231, TRUE, NULL, now()),
  ('CEC-MOC', NULL, 'Centro de Educación Continua, Unidad Los Mochis', 'CEC Los Mochis', 'Centro', 'Unidades Académicas de Educación Continua', 1, 232, TRUE, NULL, now()),
  ('CEC-MAZ', NULL, 'Centro de Educación Continua, Unidad Mazatlán', 'CEC Mazatlán', 'Centro', 'Unidades Académicas de Educación Continua', 1, 233, TRUE, NULL, now()),
  ('CEC-MORA', NULL, 'Centro de Educación Continua, Unidad Morelia', 'CEC Morelia', 'Centro', 'Unidades Académicas de Educación Continua', 1, 234, TRUE, NULL, now()),
  ('CEC-MOR', NULL, 'Centro de Educación Continua, Unidad Morelos', 'CEC Morelos', 'Centro', 'Unidades Académicas de Educación Continua', 1, 235, TRUE, NULL, now()),
  ('CEC-OAX', NULL, 'Centro de Educación Continua, Unidad Oaxaca', 'CEC Oaxaca', 'Centro', 'Unidades Académicas de Educación Continua', 1, 236, TRUE, NULL, now()),
  ('CEC-REY', NULL, 'Centro de Educación Continua, Unidad Reynosa', 'CEC Reynosa', 'Centro', 'Unidades Académicas de Educación Continua', 1, 237, TRUE, NULL, now()),
  ('CEC-TAM', NULL, 'Centro de Educación Continua, Unidad Tampico', 'CEC Tampico', 'Centro', 'Unidades Académicas de Educación Continua', 1, 238, TRUE, NULL, now()),
  ('CEC-TIJ', NULL, 'Centro de Educación Continua, Unidad Tijuana', 'CEC Tijuana', 'Centro', 'Unidades Académicas de Educación Continua', 1, 239, TRUE, NULL, now()),
  ('CEC-TLAX', NULL, 'Centro de Educación Continua, Unidad Tlaxcala', 'CEC Tlaxcala', 'Centro', 'Unidades Académicas de Educación Continua', 1, 240, TRUE, NULL, now()),
  ('CDCYT', NULL, 'Centro de Difusión de Ciencia y Tecnología', 'CDCyT', 'Centro', 'Unidades Académicas de Apoyo Educativo', 1, 242, TRUE, NULL, now()),
  ('CENLEX-ZAC', NULL, 'Centro de Lenguas Extranjeras, Unidad Zacatenco', 'CENLEX Zacatenco', 'Centro', 'Unidades Académicas de Apoyo Educativo', 1, 244, TRUE, NULL, now()),
  ('CENLEX-ST', NULL, 'Centro de Lenguas Extranjeras, Unidad Santo Tomás', 'CENLEX Santo Tomás', 'Centro', 'Unidades Académicas de Apoyo Educativo', 1, 245, TRUE, NULL, now()),
  ('CITP', NULL, 'Coordinación Institucional de Tutoría Politécnica', 'CITP', 'Coordinación', 'Unidades Académicas de Apoyo Educativo', 1, 246, TRUE, NULL, now()),
  ('CGFIE', NULL, 'Coordinación General de Formación e Innovación Educativa', 'CGFIE', 'Coordinación', 'Órganos y Áreas de la Administración Central', 1, 248, TRUE, NULL, now()),
  ('CGFIE.1', 'CGFIE', 'Dirección de Formación y Desarrollo Profesional', NULL, 'Dirección', 'Órganos y Áreas de la Administración Central', 2, 249, TRUE, NULL, now()),
  ('CGFIE.2', 'CGFIE', 'Dirección de Innovación e Investigación Educativa', NULL, 'Dirección', 'Órganos y Áreas de la Administración Central', 2, 250, TRUE, NULL, now()),
  ('POLIVIRTUAL', NULL, 'Unidad Politécnica para la Educación Virtual', 'POLIVIRTUAL', 'Unidad', 'Órganos y Áreas de la Administración Central', 1, 251, TRUE, NULL, now()),
  ('CPS', NULL, 'Coordinación Politécnica para la Sustentabilidad', 'CPS', 'Coordinación', 'Órganos y Áreas de la Administración Central', 1, 254, TRUE, NULL, now()),
  ('POLIINCUBA', NULL, 'Centro de Incubación de Empresas de Base Tecnológica', 'POLI-INCUBA', 'Centro', 'Unidades de Apoyo a la Innovación Educativa', 1, 256, TRUE, NULL, now()),
  ('POLIEMPRESARIAL', NULL, 'Unidad Politécnica para el Desarrollo y la Competitividad Empresarial', 'POLIEMPRESARIAL', 'Unidad', 'Unidades de Apoyo a la Innovación Educativa', 1, 257, TRUE, NULL, now()),
  ('TECHNOPOLI', NULL, 'Unidad de Desarrollo Tecnológico', 'TECHNOPOLI', 'Unidad', 'Unidades de Apoyo a la Innovación Educativa', 1, 258, TRUE, NULL, now()),
  ('CDA', NULL, 'Centro de Desarrollo Aeroespacial', 'CDA', 'Centro', 'Unidades de Apoyo a la Innovación Educativa', 1, 259, TRUE, NULL, now()),
  ('CNMN', NULL, 'Centro de Nanociencias y Micro Nanotecnologías', NULL, 'Centro', 'Unidades de Apoyo a la Innovación Educativa', 1, 260, TRUE, NULL, now()),
  ('INCUBA-HGO', NULL, 'Unidad Incubadora de Empresas de Base Tecnológica "Hidalgo"', NULL, 'Unidad', 'Unidades de Apoyo a la Innovación Educativa', 1, 261, TRUE, NULL, now()),
  ('INCUBA-MOR', NULL, 'Unidad Incubadora de Empresas de Base Tecnológica "Morelos"', NULL, 'Unidad', 'Unidades de Apoyo a la Innovación Educativa', 1, 262, TRUE, NULL, now()),
  ('CLUSTER-VER', NULL, 'Cluster Politécnico, Veracruz', NULL, 'Cluster', 'Unidades Educativas Vinculadas a Ciencia, Tecnología, Investigación y Desarrollo Empresarial: Clusters Politécnicos', 1, 264, TRUE, NULL, now());
